/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MlRouteImport } from './routes/ml'
import { Route as InternshipRouteImport } from './routes/internship'
import { Route as GymRouteImport } from './routes/gym'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as DsaRouteImport } from './routes/dsa'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as IndexRouteImport } from './routes/index'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MlRoute = MlRouteImport.update({
  id: '/ml',
  path: '/ml',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipRoute = InternshipRouteImport.update({
  id: '/internship',
  path: '/internship',
  getParentRoute: () => rootRouteImport,
} as any)
const GymRoute = GymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const DsaRoute = DsaRouteImport.update({
  id: '/dsa',
  path: '/dsa',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/development': typeof DevelopmentRoute
  '/dsa': typeof DsaRoute
  '/focus': typeof FocusRoute
  '/gym': typeof GymRoute
  '/internship': typeof InternshipRoute
  '/ml': typeof MlRoute
  '/notes': typeof NotesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subjects': typeof SubjectsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/development': typeof DevelopmentRoute
  '/dsa': typeof DsaRoute
  '/focus': typeof FocusRoute
  '/gym': typeof GymRoute
  '/internship': typeof InternshipRoute
  '/ml': typeof MlRoute
  '/notes': typeof NotesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subjects': typeof SubjectsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/development': typeof DevelopmentRoute
  '/dsa': typeof DsaRoute
  '/focus': typeof FocusRoute
  '/gym': typeof GymRoute
  '/internship': typeof InternshipRoute
  '/ml': typeof MlRoute
  '/notes': typeof NotesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subjects': typeof SubjectsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/development'
    | '/dsa'
    | '/focus'
    | '/gym'
    | '/internship'
    | '/ml'
    | '/notes'
    | '/sitemap.xml'
    | '/subjects'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/development'
    | '/dsa'
    | '/focus'
    | '/gym'
    | '/internship'
    | '/ml'
    | '/notes'
    | '/sitemap.xml'
    | '/subjects'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/development'
    | '/dsa'
    | '/focus'
    | '/gym'
    | '/internship'
    | '/ml'
    | '/notes'
    | '/sitemap.xml'
    | '/subjects'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevelopmentRoute: typeof DevelopmentRoute
  DsaRoute: typeof DsaRoute
  FocusRoute: typeof FocusRoute
  GymRoute: typeof GymRoute
  InternshipRoute: typeof InternshipRoute
  MlRoute: typeof MlRoute
  NotesRoute: typeof NotesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubjectsRoute: typeof SubjectsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml': {
      id: '/ml'
      path: '/ml'
      fullPath: '/ml'
      preLoaderRoute: typeof MlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internship': {
      id: '/internship'
      path: '/internship'
      fullPath: '/internship'
      preLoaderRoute: typeof InternshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym': {
      id: '/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof GymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa': {
      id: '/dsa'
      path: '/dsa'
      fullPath: '/dsa'
      preLoaderRoute: typeof DsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevelopmentRoute: DevelopmentRoute,
  DsaRoute: DsaRoute,
  FocusRoute: FocusRoute,
  GymRoute: GymRoute,
  InternshipRoute: InternshipRoute,
  MlRoute: MlRoute,
  NotesRoute: NotesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubjectsRoute: SubjectsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
